// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Album struct {
	ID         int64              `json:"id"`
	ArtistID   int32              `json:"artist_id"`
	Title      string             `json:"title"`
	ReleasedAt pgtype.Date        `json:"released_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ArtistAnalytic struct {
	ID                int64       `json:"id"`
	ArtistID          pgtype.Int4 `json:"artist_id"`
	MusicID           pgtype.Int4 `json:"music_id"`
	Listens           pgtype.Int4 `json:"listens"`
	PointsFromListens pgtype.Int4 `json:"points_from_listens"`
}

type ArtistProfile struct {
	ID         int64              `json:"id"`
	UserID     int32              `json:"user_id"`
	PublicName string             `json:"public_name"`
	Bio        pgtype.Text        `json:"bio"`
	BannerUrl  pgtype.Text        `json:"banner_url"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Disco struct {
	ID          int64              `json:"id"`
	AlbumID     int32              `json:"album_id"`
	Format      pgtype.Text        `json:"format"`
	Edition     pgtype.Text        `json:"edition"`
	CoverUrl    pgtype.Text        `json:"cover_url"`
	PricePoints int32              `json:"price_points"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ListeningHistory struct {
	ID           int64              `json:"id"`
	UserID       pgtype.Int4        `json:"user_id"`
	MusicID      pgtype.Int4        `json:"music_id"`
	ListenedAt   pgtype.Timestamptz `json:"listened_at"`
	PointsEarned pgtype.Int4        `json:"points_earned"`
}

type Music struct {
	ID        int64              `json:"id"`
	AlbumID   int32              `json:"album_id"`
	Title     string             `json:"title"`
	LengthSec pgtype.Int4        `json:"length_sec"`
	TrackNum  pgtype.Int4        `json:"track_num"`
	AudioUrl  string             `json:"audio_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	Cpf          pgtype.Text        `json:"cpf"`
	Role         string             `json:"role"`
	Points       pgtype.Int4        `json:"points"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserDisco struct {
	UserID     int32              `json:"user_id"`
	DiscoID    int32              `json:"disco_id"`
	UnlockedAt pgtype.Timestamptz `json:"unlocked_at"`
}
